### ISSUE TITLE
Art Space app: Android Basics with Compose

### ISSUE THREAD

**Issue by bmcneilece** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#44] opened 2023-01-05 15:46 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-art-space?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-art-space#4

**In which task and step of the codelab can this issue be found?**
Last Step, comparing my solution to that of developers

**Describe the problem**
Can the code for the Artspace app get added to a repository so we can see the approach of the development team?

**Steps to reproduce?**
NA

**Versions**
NA

**Additional information**
NA

**Comment by sc-gds-lxl** [comment] 2023-02-07 23:49
Closing, functioning as intended.

**Closed by sc-gds-lxl** 2023-02-07 23:49 UTC
