### ISSUE TITLE
Create an interactive Dice Roller app: Android Basics with Compose

### ISSUE THREAD

**Issue by RitikaGuleria** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#23] opened 2022-09-23 12:11 UTC
Unable to download photos from your provided link.

**Comment by osuleymanova** [comment] 2022-10-27 21:03
@RitikaGuleria 
Could you please provide the link where you tried to download the photos?

**Comment by osuleymanova** [comment] 2023-01-10 00:25
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2023-01-10 00:25 UTC
