### ISSUE TITLE
Practice problems Unit 2 Pathway 1: Android Basics with Compose

### ISSUE THREAD

**Issue by coclrc** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#31] opened 2022-11-05 17:36 UTC
A ---
name: Practice problems unit 2 pathway 1 issue template
about: Issue template for Unit 1 | Pathway 1 | Practice Problems
title: 'Practice problems Unit 2 Pathway 1: Android Basics with Compose'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-kotlin-fundamentals-practice-problems?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-kotlin-fundamentals-practice-problems#8

**In which task and step of the codelab can this issue be found?**
9. Code de solution
Enchère spéciale
Le code

**Describe the problem**
Curly braces are missing
And the function auctionPrice() doesn't work

**Versions**
_Android Studio version:_  -
_API version of the emulator:_  -

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/117535508/200133533-18cff7d8-cc88-4a43-bcad-40a1b2a3c328.png)

**Comment by angiesasmita** [comment] 2022-11-06 14:04
Hi @coclrc , We are unable to replicate the issue you mentioned. here's a screenshot of the code running on playground: 
![image](https://user-images.githubusercontent.com/10851617/200175221-23821824-7b84-45f4-be85-844dd13f5e67.png)

Note that a Kotlin class does not need the body curly braces if there is nothing to be added.

**Comment by osuleymanova** [comment] 2023-01-10 01:17
The issue is closed as not reproducible.

**Closed by osuleymanova** 2023-01-10 01:17 UTC
