### ISSUE TITLE
Use nullability in Kotlin: Android Basics in Compose

### ISSUE THREAD

**Issue by perdiDev** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#26] opened 2022-10-07 00:47 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

That not operator  .  but operator ? 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-10-27 21:04
@perdiDev 
Please provide the required details while reporting an issue so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment] 2022-11-17 01:45
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2022-11-17 01:45 UTC
